/*
 * osynth host port — sdkconfig.h
 *
 * On hardware this file is generated by Kconfig from
 * components/synth_core/Kconfig.projbuild. Here it is written by hand, and it
 * is the single place the standalone build declares its shape: everything else
 * in the port is mechanism, and this is policy.
 *
 * Two rules for editing it:
 *
 *   1. A symbol that is *off* is left undefined, never defined to 0.
 *      synth_config.h tests most of these with #ifdef, so a `#define X 0`
 *      would read as "on" and turn a feature on by looking like it was off.
 *      Kconfig behaves the same way, which is why the firmware is written
 *      against it.
 *   2. Anything that names a pin, a codec or a bus does not belong here. The
 *      files that read those are not in the host build, and adding a GPIO
 *      number for a peripheral that does not exist would be inventing a board.
 */
#pragma once

/* ---- target -------------------------------------------------------------
 *
 * None of CONFIG_IDF_TARGET_ESP32 / _ESP32S3 / _ESP32P4 is defined, on
 * purpose: synth_config.h dispatches on exactly those three and its #else is
 * an #error, so the host branch there keys off SYNTH_TARGET_HOST instead.
 *
 * CONFIG_IDF_TARGET is still a string because two places print it -- the boot
 * banner and the protocol's INFO characteristic, which is where the app's
 * `synthTarget` property comes from. Reporting "host" there is what lets the
 * app tell a standalone engine from a connected instrument without a second
 * mechanism. */
#define CONFIG_IDF_TARGET "host"

/* SYNTH_TARGET_HOST -- what synth_config.h dispatches on instead -- is NOT
 * defined here. It comes from the build system
 * (target_compile_definitions in port/host/CMakeLists.txt), and it has to:
 * sources that guard an #include on it ask the question before they have
 * included this file, so a definition here would be invisible exactly where it
 * matters most. See the note beside that line for the failure it caused. */

/* ---- audio engine -------------------------------------------------------
 *
 * The block is 64 frames, the firmware's own. It was 256 here, and the reason
 * given was the render deadline: 64 frames is 1.33 ms, which an RTOS with a
 * pinned max-priority task meets and a general-purpose OS does not reliably.
 * That reasoning was about the wrong thing. The render thread does not have a
 * 1.33 ms deadline on this port -- sink_miniaudio's ring is sized in *device
 * periods*, not in render blocks, so the thread is paced by a blocking write
 * against a ring several periods deep and simply produces four small blocks
 * where it used to produce one large one. Same work, same slack; what changes
 * is the wakeup rate, 750/s instead of 187/s, and on a host that is cheap.
 *
 * What 256 cost was the sound. The engine is full of quantities that are per
 * *block* rather than per second, so quadrupling the block quadrupled them
 * all, and the standalone build stopped being the same instrument:
 *
 *   - kParamSlew (synth_smooth.h) and kMixSlew (fx.cpp) are one-pole
 *     coefficients per block. Both are documented against "750 blocks/s";
 *     at 187 every smoothed parameter and every FX bypass crossfade took
 *     360 ms to settle instead of 90.
 *   - kTimeSlew (fx.cpp): the delay's tape glide, 110 ms -> 440 ms.
 *   - The compressor computes its gain once per block from that block's peak.
 *     fx.comp.attack has a 1 ms floor precisely because the floor is the
 *     block period; at 5.33 ms the control was lying over most of its range.
 *   - The FX LFOs, the phaser's coefficients and the granular delay's grain
 *     spawns all land on the block grid. An LFO near its 20 Hz ceiling had
 *     under four steps per cycle, and grain onsets clumped at 187 Hz instead
 *     of 750 -- audible as a pitch, not as a texture.
 *   - adsr_block() lands stage boundaries on block edges, so a 1 ms attack
 *     really was 5.33 ms and every pluck arrived soft.
 *
 * None of that is reachable by retuning constants: four of the six are grids,
 * not coefficients. Matching the firmware's block is what makes the two builds
 * one instrument, and it takes 4 ms off the output latency as a side effect.
 *
 * Voices are the firmware's 8, and this is a parity number rather than a
 * capacity one. It was 16 -- the hardware ceiling was CPU and IRAM, and
 * neither binds here -- until it turned out that the voice count is not only a
 * polyphony setting. synth_voice.cpp stages every voice at
 *
 *     kVoiceGain = 1.0f / SYNTH_VOICES
 *
 * so that a full-polyphony chord sums to 1.0, and graph_render.cpp stages the
 * modular engine's rows the same way. Doubling the voices therefore halves the
 * level of every single note: the standalone build ran 6.02 dB under the
 * instrument on every patch of every engine, and that is not a volume trim,
 * because most of what it feeds is calibrated in absolute dBFS --
 *
 *   - the drum bus is NOT staged this way, so the synth sat 6 dB under the
 *     drums here and nowhere else;
 *   - fx.comp's threshold, fx.lim's -2 dBFS ceiling, the NR/ANR thresholds and
 *     the voice-bus soft_clip() (whose "nominal full polyphony sums to 1.0"
 *     was simply false at 16) all moved relative to the signal;
 *   - the wetreverb algorithm quantises its wet output through a fixed-scale
 *     12-bit gain-ranged stage at about -78 dBFS (fx_reverb_wet.cpp, the
 *     Lexicon 224 trick). Its step does not scale with the signal, so 6 dB of
 *     input loss is 6 dB less room above the dither and the tail audibly
 *     coarsens. It is the algorithm this showed up in first.
 *
 * Keeping 16 would have meant referencing the headroom to a fixed 8 and
 * letting the bus clip past eight notes -- trading a level error for a
 * distortion the instrument cannot produce. Matching the count instead makes
 * the two builds identical for the same input, which is the whole point of
 * compiling the same sources. */
#define CONFIG_OSYNTH_SAMPLE_RATE 48000
#define CONFIG_OSYNTH_BLOCK_SIZE  64
#define CONFIG_OSYNTH_VOICES      8
#define CONFIG_OSYNTH_HEARTBEAT_MS 5000

/* ---- memory -------------------------------------------------------------
 *
 * CONFIG_SPIRAM is on, and it has to be: it is the gate on the looper
 * (looper.cpp:2733 stubs the whole component without it), on the sequencer's
 * full 8x8 model (seq_model.h:44), and on the large FX lines (fx.cpp:133).
 * Full parity means all three.
 *
 * What it selects here is the budgeted pool in port/host's esp_heap_caps
 * shim, not a real second memory. The budget below is what
 * heap_caps_get_free_size(MALLOC_CAP_SPIRAM) answers with, and looper_init()
 * turns that answer into the "max n s" the app draws -- so it is a promise
 * about recording time, and it should be a number the host can really give.
 * 256 MB on a desktop is roughly 25 minutes of stereo loop pool.
 *
 * A mobile build should lower both through heap_caps_host_set_budgets()
 * before any component initialises. */
#define CONFIG_SPIRAM 1
#define OSYNTH_HOST_SPIRAM_BUDGET_BYTES   (256u * 1024u * 1024u)
#define OSYNTH_HOST_INTERNAL_BUDGET_BYTES (32u * 1024u * 1024u)

/* ---- features on --------------------------------------------------------- */

/* The modular patch graph: an app screen depends on it, so parity needs it. */
#define CONFIG_OSYNTH_ENABLE_MODULAR 1

/* Looper persistence, on the file-backed store rather than the raw-flash one.
 * SD here means "a mounted filesystem" -- port/host replaces the card bring-up
 * and leaves the file I/O, which is already plain stdio. */
#define CONFIG_OSYNTH_LOOP_PERSIST  1
#define CONFIG_OSYNTH_LOOP_STORE_SD 1

/* Recordable sample kits (S44).
 *
 * Eight kits sharing a 4 MB pool, eight seconds per take -- the firmware's own
 * defaults, and the pool comes out of the budget above rather than out of real
 * PSRAM.
 *
 * These were off while the storage shim was being written, because asking for
 * kits enables the block at drum_kit.cpp's "SD-card and user kits" guard, and
 * that block used to be SDSPI, FAT and card bring-up with no host equivalent.
 * It now has one: the mount is a directory under the data root, and everything
 * below the mount was always plain stdio. */
#define CONFIG_OSYNTH_SAMPLE_KITS    8
#define CONFIG_OSYNTH_SAMPLE_POOL_KB 4096
#define CONFIG_OSYNTH_SAMPLE_MAX_SEC 8

/* ---- features off -------------------------------------------------------
 *
 * Left undefined rather than defined to 0 -- see rule 1 at the top. Listed
 * here with reasons because "why is there no USB audio in the standalone
 * build" is a question worth answering once in the place that decides it.
 *
 *   CONFIG_OSYNTH_ENABLE_BLE          the app reaches the engine in-process
 *                                     through ctrl_proto; there is no link.
 *   CONFIG_OSYNTH_ENABLE_I2S_DAC      output is miniaudio, not an I2S port.
 *   CONFIG_OSYNTH_ENABLE_I2S_LINE_IN  input arrives from miniaudio's capture
 *                                     side; the host branch in synth_config.h
 *                                     is what will turn SYNTH_ENABLE_LINE_IN
 *                                     on without claiming an I2S port.
 *   CONFIG_OSYNTH_ENABLE_MIC_IN       one host capture device, so a second
 *                                     source would give in.source a selector
 *                                     with one usable position.
 *   CONFIG_OSYNTH_ENABLE_LOCAL_UI     no LCD or encoders.
 *   CONFIG_OSYNTH_ENABLE_SERIAL_MIDI  no UART; host MIDI comes in through
 *                                     midi_route_channel_message().
 *   CONFIG_OSYNTH_USB_AUDIO_TAP       needs the USB device stack.
 *   CONFIG_OSYNTH_FRONTEND_ES8388     no codec to configure.
 *   CONFIG_OSYNTH_MIC_CODEC_ES8311    likewise.
 *   CONFIG_OSYNTH_DRUM_SD_KITS        that option is for loading a *prepared*
 *                                     kit off a card; the sample-kit store
 *                                     above already opens the same directory
 *                                     and is what the app's Kit page drives.
 *   CONFIG_OSYNTH_RENDER_IN_IRAM      there is no IRAM; SYNTH_RENDER_IRAM
 *                                     expands to nothing (esp_attr.h).
 *   CONFIG_OSYNTH_SPLIT_RENDER        the two-core pipeline is a P4 answer to
 *                                     that chip's interrupt placement and
 *                                     costs a block of latency to get.
 *
 * And one that is off for a licence rather than a feature:
 *
 *   CONFIG_OSYNTH_FX_GPL              MVerb and DuskVerb are GPL-3. osyntho
 *                                     is MIT, and linking them in would make
 *                                     the app a GPL-3 combined work. The
 *                                     host CMake also omits the sources, the
 *                                     same way components/fx_gpl does.
 */
