/*
 * osynth host port — sdkconfig.h
 *
 * On hardware this file is generated by Kconfig from
 * components/synth_core/Kconfig.projbuild. Here it is written by hand, and it
 * is the single place the standalone build declares its shape: everything else
 * in the port is mechanism, and this is policy.
 *
 * Two rules for editing it:
 *
 *   1. A symbol that is *off* is left undefined, never defined to 0.
 *      synth_config.h tests most of these with #ifdef, so a `#define X 0`
 *      would read as "on" and turn a feature on by looking like it was off.
 *      Kconfig behaves the same way, which is why the firmware is written
 *      against it.
 *   2. Anything that names a pin, a codec or a bus does not belong here. The
 *      files that read those are not in the host build, and adding a GPIO
 *      number for a peripheral that does not exist would be inventing a board.
 */
#pragma once

/* ---- target -------------------------------------------------------------
 *
 * None of CONFIG_IDF_TARGET_ESP32 / _ESP32S3 / _ESP32P4 is defined, on
 * purpose: synth_config.h dispatches on exactly those three and its #else is
 * an #error, so the host branch there keys off SYNTH_TARGET_HOST instead.
 *
 * CONFIG_IDF_TARGET is still a string because two places print it -- the boot
 * banner and the protocol's INFO characteristic, which is where the app's
 * `synthTarget` property comes from. Reporting "host" there is what lets the
 * app tell a standalone engine from a connected instrument without a second
 * mechanism. */
#define CONFIG_IDF_TARGET "host"

/* SYNTH_TARGET_HOST -- what synth_config.h dispatches on instead -- is NOT
 * defined here. It comes from the build system
 * (target_compile_definitions in port/host/CMakeLists.txt), and it has to:
 * sources that guard an #include on it ask the question before they have
 * included this file, so a definition here would be invisible exactly where it
 * matters most. See the note beside that line for the failure it caused. */

/* ---- audio engine -------------------------------------------------------
 *
 * The block is 256 frames rather than the firmware's 64. That is the one
 * number this port most needs to differ on: 64 frames is 1.33 ms, which an
 * RTOS with a pinned max-priority task meets and a general-purpose OS does
 * not reliably. 256 gives the render thread 5.33 ms of slack per block at the
 * cost of the same in output latency, which is still below the threshold
 * where playing an instrument feels wrong.
 *
 * Voices go to 16 because the ceiling on hardware was CPU and IRAM, and
 * neither is the binding constraint here. */
#define CONFIG_OSYNTH_SAMPLE_RATE 48000
#define CONFIG_OSYNTH_BLOCK_SIZE  256
#define CONFIG_OSYNTH_VOICES      16
#define CONFIG_OSYNTH_HEARTBEAT_MS 5000

/* ---- memory -------------------------------------------------------------
 *
 * CONFIG_SPIRAM is on, and it has to be: it is the gate on the looper
 * (looper.cpp:2733 stubs the whole component without it), on the sequencer's
 * full 8x8 model (seq_model.h:44), and on the large FX lines (fx.cpp:133).
 * Full parity means all three.
 *
 * What it selects here is the budgeted pool in port/host's esp_heap_caps
 * shim, not a real second memory. The budget below is what
 * heap_caps_get_free_size(MALLOC_CAP_SPIRAM) answers with, and looper_init()
 * turns that answer into the "max n s" the app draws -- so it is a promise
 * about recording time, and it should be a number the host can really give.
 * 256 MB on a desktop is roughly 25 minutes of stereo loop pool.
 *
 * A mobile build should lower both through heap_caps_host_set_budgets()
 * before any component initialises. */
#define CONFIG_SPIRAM 1
#define OSYNTH_HOST_SPIRAM_BUDGET_BYTES   (256u * 1024u * 1024u)
#define OSYNTH_HOST_INTERNAL_BUDGET_BYTES (32u * 1024u * 1024u)

/* ---- features on --------------------------------------------------------- */

/* The modular patch graph: an app screen depends on it, so parity needs it. */
#define CONFIG_OSYNTH_ENABLE_MODULAR 1

/* Looper persistence, on the file-backed store rather than the raw-flash one.
 * SD here means "a mounted filesystem" -- port/host replaces the card bring-up
 * and leaves the file I/O, which is already plain stdio. */
#define CONFIG_OSYNTH_LOOP_PERSIST  1
#define CONFIG_OSYNTH_LOOP_STORE_SD 1

/* Recordable sample kits (S44) -- STAGED OFF, not cut.
 *
 * Full parity wants these, and the sampler engine and its parameters are
 * compiled in either way: sampler.cpp gates on `SYNTH_SAMPLE_KITS == 0` at
 * runtime, so the controls exist and refuse takes with a reason rather than
 * going missing. What is off is the storage.
 *
 * The reason is drum_kit.cpp:181, where the user-kit store is behind
 * `#if CONFIG_OSYNTH_DRUM_SD_KITS || SYNTH_SAMPLE_KITS > 0` -- so asking for
 * kits pulls in 880 lines of SDSPI + FAT + sdmmc card bring-up, which is the
 * step-5 storage shim and not something to fake now. With this at 0 that block
 * compiles out to the stubs already written beside it
 * (drum_kit.cpp:1050-1060), and the factory ROM kit still loads.
 *
 * Restore these three to 8 / 4096 / 8 when the storage shim lands. The pool
 * draws from the budget above. */
#define CONFIG_OSYNTH_SAMPLE_KITS    0
#define CONFIG_OSYNTH_SAMPLE_POOL_KB 0
#define CONFIG_OSYNTH_SAMPLE_MAX_SEC 1

/* ---- features off -------------------------------------------------------
 *
 * Left undefined rather than defined to 0 -- see rule 1 at the top. Listed
 * here with reasons because "why is there no USB audio in the standalone
 * build" is a question worth answering once in the place that decides it.
 *
 *   CONFIG_OSYNTH_ENABLE_BLE          the app reaches the engine in-process
 *                                     through ctrl_proto; there is no link.
 *   CONFIG_OSYNTH_ENABLE_I2S_DAC      output is miniaudio, not an I2S port.
 *   CONFIG_OSYNTH_ENABLE_I2S_LINE_IN  input arrives from miniaudio's capture
 *                                     side; the host branch in synth_config.h
 *                                     is what will turn SYNTH_ENABLE_LINE_IN
 *                                     on without claiming an I2S port.
 *   CONFIG_OSYNTH_ENABLE_MIC_IN       one host capture device, so a second
 *                                     source would give in.source a selector
 *                                     with one usable position.
 *   CONFIG_OSYNTH_ENABLE_LOCAL_UI     no LCD or encoders.
 *   CONFIG_OSYNTH_ENABLE_SERIAL_MIDI  no UART; host MIDI comes in through
 *                                     midi_route_channel_message().
 *   CONFIG_OSYNTH_USB_AUDIO_TAP       needs the USB device stack.
 *   CONFIG_OSYNTH_FRONTEND_ES8388     no codec to configure.
 *   CONFIG_OSYNTH_MIC_CODEC_ES8311    likewise.
 *   CONFIG_OSYNTH_DRUM_SD_KITS        the sample-kit store covers this, and
 *                                     it is the one the app's Kit page uses.
 *   CONFIG_OSYNTH_RENDER_IN_IRAM      there is no IRAM; SYNTH_RENDER_IRAM
 *                                     expands to nothing (esp_attr.h).
 *   CONFIG_OSYNTH_SPLIT_RENDER        the two-core pipeline is a P4 answer to
 *                                     that chip's interrupt placement and
 *                                     costs a block of latency to get.
 *
 * And one that is off for a licence rather than a feature:
 *
 *   CONFIG_OSYNTH_FX_GPL              MVerb and DuskVerb are GPL-3. osyntho
 *                                     is MIT, and linking them in would make
 *                                     the app a GPL-3 combined work. The
 *                                     host CMake also omits the sources, the
 *                                     same way components/fx_gpl does.
 */
