#!/usr/bin/env python3
"""Embed a binary file as a C array, for the host port.

The ESP-IDF build embeds the drum kit with `target_add_binary_data`, which runs
objcopy and produces linker symbols named `_binary_<file>_start` / `_end`.
Those are not valid C identifiers, so drum_kit.cpp reaches them through GCC's
`asm("...")` label syntax -- which MSVC does not have.

So the host build generates the same bytes as an ordinary C array with ordinary
identifiers, and drum_kit.cpp declares them plainly under `#if defined(_MSC_VER)`.
Same data, same names in the source, a different route to the linker.

The array is `const` so it lands in read-only data, which is the nearest thing
a host has to the flash-mapped `.rodata` the firmware gets. On the ESP32 the
kit costs zero RAM because it is read in place through the flash cache; here it
is part of the image either way.

Usage:
    python tools/bin2c.py --in tools/out/drumkit.bin \\
                          --out build/drumkit_blob.c \\
                          --symbol drumkit_bin
    python tools/bin2c.py --empty --out build/drumkit_blob.c --symbol drumkit_bin
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Bytes per emitted line. 16 keeps the generated file readable if anyone opens
# it, and keeps the line count sane for a few-hundred-KB payload.
PER_LINE = 16


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", help="binary file to embed")
    ap.add_argument("--out", required=True, help="C file to write")
    ap.add_argument("--symbol", required=True,
                    help="base symbol name; _start and _end are appended")
    ap.add_argument("--empty", action="store_true",
                    help="emit a zero-length blob (no source file available)")
    args = ap.parse_args()

    if args.empty or not args.src:
        data = b""
        source = "(none -- empty blob)"
    else:
        path = Path(args.src)
        if not path.is_file():
            print(f"bin2c: {path} does not exist", file=sys.stderr)
            return 1
        data = path.read_bytes()
        source = path.as_posix()

    sym = args.symbol
    lines = [
        "/* Generated by tools/bin2c.py -- do not edit.",
        f" * Source: {source}",
        f" * Size:   {len(data)} bytes",
        " *",
        " * See the comment above the declarations in",
        " * components/drums/drum_kit.cpp for why the host build embeds this",
        " * as a C array rather than through objcopy-style _binary_* linker",
        " * symbols.",
        " *",
        " * The consumer declares both symbols as pointers, so _end is simply",
        " * _start plus the size -- there is no second object whose placement",
        " * would have to be reasoned about.",
        " */",
        "#include <stdint.h>",
        "",
        # A zero-length array is not standard C, so an empty blob still gets
        # one byte. _end is computed from the real size, which stays 0, and
        # the consumer treats a zero-length kit as "no kit" rather than
        # reading it.
        f"static const uint8_t g_payload[{max(len(data), 1)}] = {{",
    ]

    if data:
        for i in range(0, len(data), PER_LINE):
            chunk = data[i:i + PER_LINE]
            lines.append("    " + ",".join(f"0x{b:02x}" for b in chunk) + ",")
    else:
        lines.append("    0")

    lines += [
        "};",
        "",
        f"const uint8_t* const {sym}_start = g_payload;",
        f"const uint8_t* const {sym}_end = g_payload + {len(data)};",
        "",
    ]

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"bin2c: wrote {out_path} ({len(data)} bytes from {source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
